### ISSUE TITLE
Placing Flux Basic storage Crashes the game

### ISSUE THREAD

**Issue by icesmurf** [FTBTeam/FTB-Revelation-2#32]
* **Modpack Version**: 2.0.0-1.12.2

* **Issue**: Placing Flux Basic storage Crashes the game

* **Link to Log or Crash File Paste**: 
[00:04:55] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString(UUID.java:194) ~[?:1.8.0_171]
	at cofh.core.block.TileAugmentableSecure.func_145839_a(TileAugmentableSecure.java:219) ~[TileAugmentableSecure.class:?]
	at cofh.core.block.TileInventory.func_145839_a(TileInventory.java:115) ~[TileInventory.class:?]
	at cofh.thermalexpansion.block.dynamo.TileDynamoBase.func_145839_a(TileDynamoBase.java:526) ~[TileDynamoBase.class:?]
	at cofh.thermalexpansion.block.dynamo.TileDynamoCompression.func_145839_a(TileDynamoCompression.java:182) ~[TileDynamoCompression.class:?]
	at elucent.elulib.network.MessageTEUpdate$MessageHolder.lambda$onMessage$0(MessageTEUpdate.java:49) ~[MessageTEUpdate$MessageHolder.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more

* **Is it Repeatable?**: Yes every Time.

* **Mod/s Affected**: I suspect it's the flux mod

* **Known Fix**: None

**Comment by Boomflex** [comment]
This has been fixed in an upcoming update v2.1.0

As you can see I posted a bunch of them.

https://i.imgur.com/jkhgaGO.jpg
