### ISSUE TITLE
Game crashes immediately after starting

### ISSUE THREAD

**Issue by Alledish** [FTBTeam/FTB-Revelation-2#391]
Hi all, I just downlodaded FTB Revelation and I'm getting a crash every time I boot the game, 

Modpack version is 3.2.1

Here is what I get after every boot

The game crashed whilst initializing game
Error: org.lwjgl.LWJGLException: Pixel format not accelerated

---- Minecraft Crash Report ----

WARNING: coremods are present:
  RandomPatches (randompatches-1.12.2-1.18.1.1.jar)
  SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  p455w0rdc0re (p455w0rdslib-1.12.2-2.2.156.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.68-core.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/23/20 7:48 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 658992168 bytes (628 MB) / 923795456 bytes (881 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
RandomPatches (randompatches-1.12.2-1.18.1.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  pl.asie.splashanimation.core.SplashProgressTransformer
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
p455w0rdc0re (p455w0rdslib-1.12.2-2.2.156.jar)
  p455w0rdslib.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.3.jar)
  
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.68-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	Launched Version: forge-14.23.5.2846
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

I'm completely new to modding so any help would be appreciated.  Also I downloaded Revelation through the twitch app if that helps anything at all.  Thanks!

**Comment by rune-san** [comment]
From your log:
`Memory: 658992168 bytes (628 MB) / 923795456 bytes (881 MB) up to 3008888832 bytes (2869 MB)`

You have too little RAM assigned to the game (less than 3GB), which is why the game is crashing while it's loading. Per the notes on the website, 4GB is the minimum. Go to either the Profile for that Minecraft Instance in Twitch, or you Global Minecraft settings in Twitch, and increase the Allocated Memory for Java to between 4 (4096MB) and 6GB (6144MB) (depending on how much you have in your computer to spare) and give it another try!
