### ISSUE TITLE
mod pack not loading net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

### ISSUE THREAD

**Issue by grant5301** [FTBTeam/FTB-Revelation-2#413]
so i was trying to play ftb revalations on 1.12 and this crash report comes up around loading in the recipes for just enough items
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)Time: 11/22/20 1:40 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:201)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:434)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:385)
	at mezz.jei.startup.UniqueItemStackListBuilder.add(UniqueItemStackListBuilder.java:25)
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:379)
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:360)
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:345)
	at mezz.jei.startup.StackHelper.expandRecipeItemStackInputs(StackHelper.java:328)
	at mezz.jei.startup.StackHelper.expandRecipeItemStackInputs(StackHelper.java:322)
	at mezz.jei.plugins.vanilla.crafting.ShapelessRecipeWrapper.getIngredients(ShapelessRecipeWrapper.java:33)
	at mezz.jei.recipes.RecipeRegistry.getIngredients(RecipeRegistry.java:285)
	at mezz.jei.recipes.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:271)
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:259)
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:231)
	at mezz.jei.recipes.RecipeRegistry.addRecipes(RecipeRegistry.java:168)
	at mezz.jei.recipes.RecipeRegistry.<init>(RecipeRegistry.java:95)
	at mezz.jei.startup.ModRegistry.createRecipeRegistry(ModRegistry.java:335)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:77)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

**Comment by Emmydobby** [comment]
Go into your twitch modpack settings --> profile options --> increase the memory settings
![1](https://user-images.githubusercontent.com/74891451/99930715-2b58e800-2da6-11eb-862c-54045ed2834f.png)

**Comment by Sunekaer** [comment]
Assign a minium of 4gb ram to the instance
